postfix-19990906

diff --git a/makedefs b/makedefs
--- a/makedefs
+++ b/makedefs
@@ -102,7 +102,7 @@ case "$SYSTEM.$RELEASE" in
 		RANLIB=echo
 		SYSLIBS="-lresolv -lsocket -lnsl"
 		case $RELEASE in
-		    5.[0-4]) CCARGS="$CCARGS -Dusleep=doze";;
+		    5.[0-4]) CCARGS="$CCARGS -DMISSING_USLEEP";;
 			  *) CCARGS="$CCARGS -DHAS_POSIX_REGEXP";;
 		esac
 		# Avoid common types of braindamage
@@ -116,11 +116,32 @@ case "$SYSTEM.$RELEASE" in
 		  esac;;
 		esac
 		;;
+   ULTRIX.4*)	SYSTYPE=ULTRIX4
+		if [ -f /usr/local/lib/libdb.a ]; then
+		    SYSLIBS="$SYSLIBS -ldb"
+		    CCARGS="$CCARGS -DHAS_DB"
+		    if [ -d /usr/local/include/db ]; then
+			CCARGS="$CCARGS -I/usr/local/include/db"
+		    fi
+		fi
+		for l in syslog resolv; do
+		    if [ -f /usr/local/lib/lib$l.a ]; then
+			SYSLIBS="$SYSLIBS -l$l"
+		    fi
+		done
+		;;
        AIX.*)	case "`uname -v`" in
 		4)	SYSTYPE=AIX4
 			# How embarrassing...
 			case "$CC" in
-			cc|*/cc|xlc|*/xlc) OPT=;;
+			cc|*/cc|xlc|*/xlc) OPT=; CCARGS="$CCARGS -w";;
+			esac
+			CCARGS="$CCARGS -D_ALL_SOURCE"
+			;;
+		3)	SYSTYPE=AIX3
+			# How embarrassing...
+			case "$CC" in
+			cc|*/cc|xlc|*/xlc) OPT=; CCARGS="$CCARGS -w";;
 			esac
 			CCARGS="$CCARGS -D_ALL_SOURCE"
 			;;
@@ -149,7 +170,7 @@ case "$SYSTEM.$RELEASE" in
 		;;
 HP-UX.A.09.*)	SYSTYPE=HPUX9
 		SYSLIBS=-ldbm
-		CCARGS="$CCARGS -Dusleep=doze"
+		CCARGS="$CCARGS -DMISSING_USLEEP"
 		if [ -f /usr/lib/libdb.a ]; then
 		    CCARGS="$CCARGS -DHAS_DB"
 		    SYSLIBS="$SYSLIBS -ldb"
@@ -157,7 +178,7 @@ HP-UX.A.09.*)	SYSTYPE=HPUX9
 		;;
 HP-UX.B.10.*)	SYSTYPE=HPUX10
 		CCARGS="$CCARGS `nm /usr/lib/libc.a 2>/dev/null |
-		    (grep usleep >/dev/null || echo '-Dusleep=doze')`"
+		    (grep usleep >/dev/null || echo '-DMISSING_USLEEP')`"
 		if [ -f /usr/lib/libdb.a ]; then
 		    CCARGS="$CCARGS -DHAS_DB"
 		    SYSLIBS=-ldb
@@ -170,6 +191,15 @@ HP-UX.B.11.*)	SYSTYPE=HPUX11
 		    SYSLIBS="$SYSLIBS -ldb"
 		fi
 		;;
+ReliantUNIX-?.5.43) SYSTYPE=ReliantUnix543
+		RANLIB=echo
+		SYSLIBS="-lresolv -lsocket -lnsl"
+		;;
+ Rhapsody.5*)	SYSTYPE=RHAPSODY5
+		# Use the native compiler by default
+		: ${CC=cc}
+		AWK=gawk
+		;;
 	 ".")	if [ -d /NextApps ]; then
 		    SYSTYPE=`hostinfo | sed -n \
 			's/^.*NeXT Mach 3.*$/NEXTSTEP3/;/NEXTSTEP3/{p;q;}'`
@@ -177,6 +207,7 @@ HP-UX.B.11.*)	SYSTYPE=HPUX11
 			SYSTYPE=`hostinfo | sed -n \
 			    's/^.*NeXT Mach 4.*$/OPENSTEP4/;/OPENSTEP4/{p;q;}'`
 		    fi
+		    : ${CC=cc}
 		    RANLIB="sleep 5; ranlib"
 		else
 		    echo "Unable to determine your system type." 1>&2; exit 1
@@ -199,9 +230,9 @@ case "$CC" in
         *) : ${OPT='-O'};;
 esac
 
-: ${CC='gcc $(WARN)'} ${OPT='-O'} ${DEBUG='-g'}
+: ${CC='gcc $(WARN)'} ${OPT='-O'} ${DEBUG='-g'} ${AWK=awk}
 
-export SYSTYPE AR ARFL RANLIB SYSLIBS CC OPT DEBUG OPTS
+export SYSTYPE AR ARFL RANLIB SYSLIBS CC OPT DEBUG AWK OPTS
 
 sed 's/  / /g' <<EOF
 SYSTYPE	= $SYSTYPE
@@ -212,4 +243,5 @@ SYSLIBS	= $AUXLIBS $SYSLIBS
 CC	= $CC $CCARGS
 OPT	= $OPT
 DEBUG	= $DEBUG
+AWK	= $AWK
 EOF
