postfix-3.1.0

diff --git a/postfix-install b/postfix-install
--- a/postfix-install
+++ b/postfix-install
@@ -183,6 +183,11 @@
 #	IBM T.J. Watson Research
 #	P.O. Box 704
 #	Yorktown Heights, NY 10598, USA
+#
+#	Wietse Venema
+#	Google, Inc.
+#	111 8th Avenue
+#	New York, NY 10011, USA
 #--
 
 # Initialize.
@@ -199,6 +204,11 @@ BACKUP_IFS="$IFS"
 # Override all LC_* settings and LANG for robustness.
 LC_ALL=C; export LC_ALL
 
+if [ -n "$SHLIB_ENV_VAR" ]; then
+    junk="${SHLIB_ENV_VAL}"
+    eval export "$SHLIB_ENV_VAR=\$junk"
+fi
+
 USAGE="Usage: $0 [name=value] [option]
     -non-interactive        Do not ask for installation parameters.
     -package                Build a ready-to-install package.
@@ -211,10 +221,11 @@ USAGE="Usage: $0 [name=value] [option]
 for arg
 do
     case $arg in
-      *=*) IFS= eval $arg; IFS="$BACKUP_IFS";;
--non-int*) non_interactive=1;;
- -package) need_install_root=install_root;;
-        *) echo "$0: Error: $USAGE" 1>&2; exit 1;;
+*[" 	"]*) echo "$0: Error: argument contains whitespace: '$arg'"; exit 1;;
+	*=*) IFS= eval $arg; IFS="$BACKUP_IFS";;
+  -non-int*) non_interactive=1;;
+   -package) need_install_root=install_root;;
+	  *) echo "$0: Error: $USAGE" 1>&2; exit 1;;
     esac
     shift
 done
@@ -590,6 +601,17 @@ do
 	exit 1
    };;
    esac
+done
+
+# Don't allow space or tab in parameter settings.
+
+for name in $CONFIG_PARAMS sample_directory
+do
+    eval junk=\$$name
+    case "$junk" in
+*"[ 	]"*) echo "$0: Error: $name value contains whitespace: '$junk'" 1>&2
+	     exit 1;;
+    esac
 done
 
 test -d $tempdir || mkdir -p $tempdir || exit 1
